api:
  deepseek:
    url: "https://deepseek/v1/chat/completions"
    api_key: "YOUR_API_KEY"
    model: "deepseek-v3-241226"
    max_tokens: 2048
    temperature: 0.7
    top_p: 0.7
    top_k: 50
    frequency_penalty: 0.5

notification:
  feishu:
    app_id: "cli_xxxxxxx"
    app_secret: ""
    robot_id: ""
    webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/"
    chat_id: "oc_xxxxxxx"
    user_emails_map:
      OPS: ["ops@example.com", "admin@example.com"]
      SECURITY: ["security@example.com"]

files:
  log_path: "processor_data.txt"
  prompt_template: "prompt_template.yaml"
  conversation: "conversation.txt"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 


